# - Manifest file 
# - a sample yaml format to create the pod

apiVersion: v1
kind: pod
metadata: 
  name: nginx-pod
spec:
  container:
  - image: nginx
    name: nginx
    ports:
    - containerPort:80