# - Manifest file 
# - a sample yaml format to create the pod

apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort:80